jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css, markdown
